package Part;
/**
 *
 * @JamesFuller
 */

/**
 * Extends the part abstract class into In House components.
 */
public class InHouse extends Part {
    private int machineId;
    /**
     * Class constructor
     * @param id part id generated by inventory
     * @param name  part name
     * @param price part price
     * @param stock the current stock
     * @param min minimum stock value
     * @param max maximum stock value
     * @param machineId the machine id for in house part
     */
    public InHouse(int id, String name, double price, int stock, int min, int max, int machineId) {
        super(id, name, price, stock, min, max);
        this.machineId = machineId;
    }

    /**
     * @return the machineId
     */
    public int getMachineId() {
        return machineId;
    }

    /**
     * @param machineId the machineId to set
     */
    public void setMachineId(int machineId) {
        this.machineId = machineId;
    }

    /**
     * Returns a string to determine if a part is outsourced or in house with a single method.
     * @return string of the machineId
     */
    public String getMachineOrCompany() {
        return String.valueOf(machineId);
    }
}
