package Part;
/**
 *
 * @JamesFuller
 */

/**
 * Extends the part abstract class into Outsourced components.
 */
public class Outsourced extends Part {
    private String companyName;

    /**
     * Class constructor
     * @param id part id generated by inventory
     * @param name  part name
     * @param price part price
     * @param stock the current stock
     * @param min minimum stock value
     * @param max maximum stock value
     * @param companyName the company name for an outsourced part
     */
    public Outsourced(int id, String name, double price, int stock, int min, int max, String companyName) {
        super(id, name, price, stock, min, max);
        this.companyName = companyName;
    }

    /**
     * @return the companyName
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * @param companyName the companyName to set
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * Returns a string to determine if a part is outsourced or in house with a single method.
     * @return the companyName
     */
    public String getMachineOrCompany() {
        return companyName;
    }
}
